### PR TITLE
feat: add experimental IHP support

### PR DESCRIPTION
**Pull request by htfab**

### CODE REVIEW

**Comment by urish** [comment]
I think the flows are different enough to keep them separated, perhaps under orfs/action.yml? WDYT?

**Comment by htfab** [comment]
I have a slight preference for keeping it together, otherwise it's easier to forget to make the same changes to both. The actions aren't as different as they look, but if you prefer, I can make them more similar by
- changing the run tag from `ihp` to `wokwi`
- putting the step that installs openroad, klayout, yosys, orfs & the ihp pdk into its own sub-action
- splitting the commit into two, the first one refactoring the sky130 code and the second one adding the ihp changes only

Would you like that?

**Comment by urish** [comment]
> I have a slight preference for keeping it together, otherwise it's easier to forget to make the same changes to both. The actions aren't as different as they look, but if you prefer, I can make them more similar by

One reason I'm in favor of splitting is because I believe we'll eventually switch to OL2 for IHP. 

Anyway, I'm happy to follow your suggestion.

**Comment by htfab** [comment]
Ok, I've split the action but also changed the run tag and refactored the sky130 code in the original action.

**Comment by urish** [comment]
Thanks!

**Pull request merged**
